[package]
name = "gamma_ray"
version = "0.1.0"
authors = ["Sebastian <Sebastian@Strobl.net>"]
edition = "2018"
license-file = "LICENSE"
repository = "https://github.com/TriedWorks/gamma_ray"
categories = ["mathematics", "science"]
keywords = ["math", "mathematics", "science", "physics"]
publish = true
description = "multipurpose math and physics crate for my projects"

[lib]
name = "gamma_ray"
path = "src/lib.rs"

[dependencies]
paste = "1.0.4"